version: "3.7"

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    volumes: 
      - ./data/mysql_data:/var/lib/mysql
      - ./libs/storage/src/main/resources/sql:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  redis:
    # 사용할 이미지
    image: redis:7.0.4
    # 컨테이너명
    container_name: redis_test
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - 6379:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ./.redis/data:/data
      - ./.redis/conf/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"