spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  config:
    import: application-storage-${spring.profiles.active}.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  port: 8000

grpc:
  port: 9090