springdoc:
  swagger-ui:
    path: "/swg"

spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  config:
    import:
      - application-storage-${spring.profiles.active}.yml
      - application-oauth.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
security:
  aes128:
    key: 1q2w3e4r5t6y7u8i

grpc:
  crawling-server:
    address: "localhost"
    port: "8080"
