spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client_name: google
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_OAUTH_CLIENT_REDIRECT_URI}
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
        provider:
          google:
            token-uri: ${GOOGLE_TOKEN_URI:https://oauth2.googleapis.com/token}
            user-info-uri: ${GOOGLE_USER_INFO_URI:GOOGLE_USER_INFO_URI:https://googleapis.com/oauth2/v2/userinfo}
            authorization-uri: ${GOOGLE_AUTHORIZTION_URI:https://accounts.google.com/o/oauth2/v2/auth}