name: deploy
on:
 pull_request:
    types: [ opened ]
    branches: [ deploy-test ]
    paths:
      - 'libs/**'
      - 'src/api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Cache gradle modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :api:build -x test
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_KEY }}
          source: "./src/api/build/libs/api.jar"
          target: "home/ubuntu/"
      - name: Run JAR file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_KEY }}
          script: |
            cd /home/ubuntu/
            pid=`ps -ef | grep "api.jar" | grep -v 'grep' | awk '{print $2}'`
            if [ $pid ]
            then
            kill $pid
            echo "Delete Prev Version"
            fi
            java -Dspring.profiles.active=dev -jar api.jar &
