name: deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ closed ] # when PR closed
    paths:
      - 'libs/**'
      - 'src/api/**'
      - 'src/crawler/**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Cache gradle modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build api server with Gradle
        run: ./gradlew :api:build -x test
      - name: Build crawler server with Gradle
        run: ./gradlew :crawler:build -x test
      - name: copy api server file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_KEY }}
          source: "./src/api/build/libs/api.jar"
          target: "./api"
      - name: copy crawler server file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_KEY }}
          source: "./src/crawler/build/libs/crawler.jar"
          target: "./crawler"
      - name: Run api JAR file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_KEY }}
          script: |
            pid=$(ps -ef | grep "api" | grep -v 'grep' | awk '{print $2}')
            if [ "$pid" ]
            then
              kill "$pid"
              echo "Delete Prev Version"
            fi
            chmod 777 ./api/src/api/build/libs/api.jar
            nohup java -Dspring.profiles.active=dev -jar ./api/src/api/build/libs/api.jar > nohup.out 2> nohup.err < /dev/null &
      - name: Run crawler JAR file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_DEV_HOST }}
          username: ${{ secrets.REMOTE_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_KEY }}
          script: |
            pid=$(ps -ef | grep "crawler" | grep -v 'grep' | awk '{print $2}')
            if [ "$pid" ]
            then
              kill "$pid"
              echo "Delete Prev Version"
            fi
            chmod 777 ./crawler/src/crawler/build/libs/crawler.jar
            nohup java -Dspring.profiles.active=dev -jar ./crawler/src/crawler/build/libs/crawler.jar > nohup.out 2> nohup.err < /dev/null &
